### ISSUE TITLE
need to get from ePromos the app been used for reviews and wishlist

### ISSUE THREAD

**Issue by idobarel1973** [idobarel1973/Customization#1]

**Comment by robinepromos** [comment]
The app will be using is called YotPo.

**Comment by idobarel1973** [comment]
@robinepromos Great, please enable it on our dashboard under the integration tab:



![Image](https://github.com/idobarel1973/Customization/assets/73065108/e6004d50-4a0f-4a1b-8afa-e8b38720c209)

**Comment by idobarel1973** [comment]
review app - yotpo - if no reviews (doesn't display it )
wishlist - default bigCommerce
