### ISSUE TITLE
epromos need to provide icons been used on this design

### ISSUE THREAD

**Issue by idobarel1973** [idobarel1973/Customization#2]

**Comment by idobarel1973** [comment]
right and left arrows on the recommendation carousel


![Image](https://github.com/idobarel1973/Customization/assets/73065108/556039c7-0404-475d-a76a-262557c25116)



filter icon


![Image](https://github.com/idobarel1973/Customization/assets/73065108/ab55f254-cc77-4943-a065-16b94d22ed87)


wishlist icon (filled and empty)


![Image](https://github.com/idobarel1973/Customization/assets/73065108/604026e3-e692-4ff6-b4e9-cc0e1d799352)

**Comment by robinepromos** [comment]
![icon-slick-right-arrow](https://github.com/idobarel1973/Customization/assets/142402922/62afd09d-5d47-47e7-869c-fae1969a065c)
![icon-slick-left-arrow](https://github.com/idobarel1973/Customization/assets/142402922/98c5b043-2ca7-48d2-bca2-120909cec01c)
![filter-close](https://github.com/idobarel1973/Customization/assets/142402922/9dd85f41-b49f-4599-9fed-10de35e2f60d)
![wishlist-heart-icon](https://github.com/idobarel1973/Customization/assets/142402922/c70dddb2-b232-4d76-8efd-22e274da74f2)
![filter-icon](https://github.com/idobarel1973/Customization/assets/142402922/cd4f9901-275e-4783-94b0-dad904df003a)

Attached are the icons. Let me know if there are more svg icon files needed.

**Comment by idobarel1973** [comment]
@robinepromos thanks!
