### ISSUE TITLE
need to get from epromos the logic behind each badge

### ISSUE THREAD

**Issue by idobarel1973** [idobarel1973/Customization#4]

**Comment by idobarel1973** [comment]
i noticed that you have a custom field named - "Product Badge"
we read the value and add this as a badge is exists - 

please confirm

**Comment by billoshea** [comment]
After discussing internally, we were hoping that badges could be dynamic. One would be on sale, as you showed us. The others would be based on the presence of a product in a certain category. Would this be possible? Ideally, we'd have:

- On Sale
-- Display if a product is on sale
-- Background: Red (#d61634)
-- Text: White (#ffffff)

- New
-- Display if a product is in the [Best New Products](https://store-3id377df4x.mybigcommerce.com/manage/products/categories/1/edit/1566) category
-- Background: Blue (#00a1e5)
-- Text: White (#ffffff)

- Best Seller
-- Display if a product is in the [ePromos Core Collection](https://store-3id377df4x.mybigcommerce.com/manage/products/categories/1/edit/1547) category
-- Background: Teal (#9de7d9)
-- Text: Black (#000000)

Please let us know if this is possible. We understand that it can be handled via the Custom Field, but are hoping to prevent duplicate work and an increased level of upkeep for our product data team.

**Comment by idobarel1973** [comment]
@idobarel1973 check the badges logic
